# Generated by Django 4.1.5 on 2023-01-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, null=True, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titte', models.CharField(max_length=200, null=True, unique=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('day_create', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=1)),
                ('category', models.ManyToManyField(related_name='post', to='api_quangcao.category')),
            ],
        ),
    ]
