# Generated by Django 4.1.5 on 2023-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quangcao', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
