# Generated by Django 4.1.5 on 2023-01-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quangcao', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default='Tin Tức', related_name='posts', to='api_quangcao.category'),
        ),
    ]
