# Generated by Django 4.1.5 on 2023-01-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quangcao', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='api_quangcao.category'),
        ),
    ]
