# Generated by Django 4.1.5 on 2023-01-28 14:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api_quangcao', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=0.5, size=[500, 300], upload_to='thumbnail_post'),
        ),
    ]
