# Generated by Django 4.1.5 on 2023-01-29 14:37

import api_quangcao.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api_quangcao', '0011_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=100, scale=0.5, size=[1000, 800], upload_to=api_quangcao.models.content_file_name),
        ),
    ]
