# Generated by Django 4.1.5 on 2023-01-29 14:53

import api_quangcao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_quangcao', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=api_quangcao.models.content_file_name),
        ),
    ]
